# Failing currently
# The error message from the worker-app-pod logs, 
# System.NotSupportedException: Authentication method not supported (Received: 10), 
# indicates that the Npgsql library used by your worker application 
# does not support the SCRAM-SHA-256 authentication method required by the 
# PostgreSQL database it is trying to connect to.

apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1


# Create the worker-app pod
# ``kubectl create -f worker-app-pod.yaml``

# Verify the worker-app pod
# ``kubectl get pods``

# Verify the worker-app pod details
# ``kubectl describe pod worker-app-pod``

# Verify the worker-app pod logs
# ``kubectl logs worker-app-pod``

# Delete the worker-app pod
# ``kubectl delete pod worker-app-pod``